import Head from 'next/head'
import { Navigations, Header, Discover, Helpus, About } from '../components'
import components from '../styles/layouts/_components.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Leafy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.ico" />
      </Head>

      <div className={components.StyledWrapper}></div>
      <Navigations />
      <Header />
      <Discover/>
      <Helpus/>
      <About/>

    </div>
  )
}
